#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# status bar
$HOME/.config/polybar/launch.sh &

# get battery when low
$HOME/.local/bin/battery_low.sh &

# notification daemon
pgrep -x dunst >> /dev/null || dunst &

# launch screensaver
pgrep -x xscreensaver >> /dev/null || xscreensaver &

# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/pid ] && mpd
sh ~/.local/bin/start-mpd.sh

# compositor
pgrep -x picom > /dev/null || picom -CG &

# launch alacritty
#pgrep -x alacritty >> /dev/null || alacritty

# auto lock when screen has inactivity
#xautolock -notify 30 -notifier "notify-send -u critical -t 10000 'The screen will be LOCKING in 30s'" -time 10 -locker "~/.local/bin/lock.sh"

#bspc monitor LVDS-1 -d 1 2 3 4 5
#bspc monitor HDMI-2 -d 6 7 8 9 0
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1.5
bspc config window_gap           3
bspc config active_border_color \#E84F4F
bspc config normal_border_color \#005ce6

bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config center_pseudo_tiled  true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
