#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#$HOME/.config/bspwm/panel/panel &

# status bar
$HOME/.config/polybar/launch.sh &

# notification daemon
killall dunst
dunst &

# compositor
killall picom
picom -G &

# auto lock when screen has inactivity
xautolock -time 10 -locker "~/.local/bin/lock.sh"

bspc monitor LVDS-1 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           7

bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config center_pseudo_tiled  true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
